### PR TITLE
Add SSWG package collections

### PR DESCRIPTION
**Pull request by finestructure**
### Motivation:

This adds the data files to manage packages following the [SSWG incubation process](https://www.swift.org/sswg/incubation-process.html). They will also be the basis for custom package collections on the Swift Package Index.

### Modifications:

Adds three files with package URLs.

To do, as discussed with @0xTim :

- [ ] make sure the YML files are configured to be processed to JSON files at the appropriate URL, probably `https://github.com/swiftlang/swift-org-website/blob/main/api/v1/install/{graduated|incubating|sandbox}.json` - perhaps they should have an `sswg-prefix`?
- [ ] update the files to reflect the latest review

### CODE REVIEW

**Comment by 0xTim** [comment]
Do you think it's worth combining these into one file? Would be easier to spot duplicate and changes etc and I think the tools should be fine

**Comment by finestructure** [comment]
Could do that but it would definitely have to _produce_ three separate files for the package collections - and that's probably not straightforward, is it?

**Comment by daveverwer** [comment]
> Nope we should be able to read a subsection of the YAML easily. I'll have a play

One YAML -> multiple output files can be done with a Jekyll generator. Take a look at what I did in `_plugins/packages.rb` for how to do it.

**Comment by 0xTim** [comment]
@finestructure https://github.com/swiftlang/swift-org-website/blob/main/_data/server-workgroup/projects.yml 😆

**Comment by 0xTim** [comment]
Closing in favour of #853

**Pull request closed without merging**
