### PR TITLE
Updated Installation via RPM section.

### PR DESCRIPTION
**Pull request by RobinBateman808**
### Motivation:

Update the text for RPM packages as suggested to help new users.

### Modifications:

Added brief lead-in sentences for Amazon Linux 2 and Centos. Added instructions.

### Result:

Provide explanations to help new users understand the purpose and instructions with clarity.

### CODE REVIEW

**Comment by RobinBateman808** [comment]
@shahmishal  - Edited this section as suggested.

**Review by 0xTim — APPROVED** [review]
These changes look good but should probably be merged after #676 or changed to point to that branch

**Comment by RobinBateman808** [comment]
@0xTim - Thank you and noted.

**Comment by RobinBateman808** [comment]
@0xTim - Thanks for the review.

**Review by federicobucchi — APPROVED** [review]

**Comment by RobinBateman808** [comment]
Hi @shahmishal - Do you want to merge this PR now that PR#676 has been implemented?

**Comment by RobinBateman808** [comment]
Closing PR as completed.

**Pull request closed without merging**
