### PR TITLE
Update links for repositories moved to the swiftlang org on GitHub

### PR DESCRIPTION
**Pull request by ahoppen**

### CODE REVIEW

**Comment by ahoppen** [comment]
@swift-ci Please test

**Comment by dempseyatgithub** [comment]
@swift-ci test

**Review by dempseyatgithub — APPROVED** [review]
These all look fine to me.

**Comment by finagolfin** [comment]
I notice you missed the blog posts and GSoC doc, as did Mishal till Alexander updated them, #731.

**Pull request merged**
