### PR TITLE
Update website repo URLs to point to new location in swiftlang organization

### PR DESCRIPTION
**Pull request by alexandersandberg**

### CODE REVIEW

**Comment by parispittman** [comment]
LGTM

**Review by shahmishal — APPROVED** [review]

**Review by parispittman — APPROVED** [review]

**Review by federicobucchi — APPROVED** [review]

**Review by dempseyatgithub — APPROVED** [review]
Reviewed and approved.

**Comment by dempseyatgithub** [comment]
@swift-ci please test

**Comment by dempseyatgithub** [comment]
@swift-ci test

**Pull request merged**
