### PR TITLE
Update documentation workgroup members

### PR DESCRIPTION
**Pull request by franklinsch**
Updates the list of members in the documentation workgroup.

cc @swiftlang/documentation-workgroup @sofiaromorales

### CODE REVIEW

**Comment by franklinsch** [comment]
Could someone also help update the GitHub @swiftlang/documentation-workgroup group and the Swift Forums `@swift-documentation-workgroup` group to reflect the latest list of members?

**Comment by alexandersandberg** [comment]
> Could someone also help update the GitHub @swiftlang/documentation-workgroup group and the Swift Forums `@swift-documentation-workgroup` group to reflect the latest list of members?

@shahmishal maybe

**Review by alexandersandberg — APPROVED** [review]

**Comment by alexandersandberg** [comment]
@swift-ci please test

**Comment by franklinsch** [comment]
Thanks! I doesn't seem like I have write access to this repo, can someone please merge?

**Review by daveverwer — APPROVED** [review]

**Pull request merged**
