### PR TITLE
Update CONTRIBUTORS-WEBSITE.txt that is generated using `./scripts/generate_contributors_list.sh`. 

### PR DESCRIPTION
**Pull request by lamtrinhdev**
### Summary:
The CONTRIBUTORS-WEBSITE.txt is outdated. Update CONTRIBUTORS-WEBSITE.txt that is generated using `./scripts/generate_contributors_list.sh`. 

### Modifications:

Update CONTRIBUTORS-WEBSITE.txt that is generated using `./scripts/generate_contributors_list.sh`. 

### Result:

Update to date the CONTRIBUTORS-WEBSITE.txt file.

### CODE REVIEW

**Comment by lamtrinhdev** [comment]
@swift-ci please test

**Comment by alexandersandberg** [comment]
@parispittman what did we plan to do with this list? I know we touched it in #732 but don't remember the intentions.

**Comment by lamtrinhdev** [comment]
If it is possible, I think we should update "CONTRIBUTORS.txt" too.

**Comment by dempseyatgithub** [comment]
> @parispittman what did we plan to do with this list? I know we touched it in #732 but don't remember the intentions.

If I remember correctly, along with the move to the swiftlang org, projects in the org were going to stop maintaining contributor files and rely on the the GitHub contributor mechanism instead. @parispittman can correct me if I am mistaken.

**Comment by parispittman** [comment]
That is correct - we are no longer using contributor.txt type files.

**Comment by lamtrinhdev** [comment]
Dear @alexandersandberg , @dempseyatgithub , @parispittman ,

Thank you for your feedback. Let me close this PR.

Thanks,
Lam

**Pull request closed without merging**
