### PR TITLE
Modernize visual appearance of grids

### PR DESCRIPTION
**Pull request by rauhul**
Updates all grids except for package grids to take a more layered
appearance matching that of the tabs.

Adds support for "prefers-contrast: more" to use the previous higher
contrast style.

Removes the many grid css styles and replaces them with a common grid
style in the elements folder than can be reused between pages.

Builds on top of #743, #749, and #751

### CODE REVIEW

**Comment by rauhul** [comment]
@swift-ci test

**Comment by rauhul** [comment]
# Before & After

## Home
Screenshot 2024-06-25 at 1 56 19 PM
Screenshot 2024-06-25 at 1 57 56 PM

## Getting Started
Screenshot 2024-06-25 at 1 56 30 PM
Screenshot 2024-06-25 at 1 58 03 PM

## Packages
Screenshot 2024-06-25 at 1 58 26 PM
Screenshot 2024-06-25 at 1 58 13 PM

## Tools
Screenshot 2024-06-25 at 1 58 39 PM
Screenshot 2024-06-25 at 1 58 46 PM

**Comment by heckj** [comment]
For my part, it lowers the reading contrast in those grey-blocked sections a bit too much. No qualms about the added visual structure blocking things out, but I'd at least toss in a request for a darker font/weighting to get the contrast back up.

**Comment by rauhul** [comment]
> For my part, it lowers the reading contrast in those grey-blocked sections a bit too much. No qualms about the added visual structure blocking things out, but I'd at least toss in a request for a darker font/weighting to get the contrast back up.

For both dark and light mode or just one specifically?

**Comment by heckj** [comment]
Ah, sorry - really just the light mode. The difference in the dark mode didn't my eyes as hard - it's a little reduced, but not to a level that makes reading more difficult for me. I'll never complain about a bit more contrast though ;-)

**Comment by dempseyatgithub** [comment]
Since the existing style is very high contrast, we should consider preserving it as a `prefers-contrast` CSS media query for accessibility users requiring high contrast. I don't think that has been a concern before with the existing style.

**Comment by dempseyatgithub** [comment]
I find the use of the orange color for call outs, for example the "Get Involved" section of the package page to draw far too much attention to that element. Getting involved is important, which is why it is in a call out box, but it is not the most important thing on the page.

I find the orange color draws the eye too much for these kind of call outs. 

Changing the link text and underline from blue to orange also make the link / call to action in the call out much less visible. Scanning the original, it is clear the box wants people to get involved with the main way of getting involved as 'Nominate packages'.

Using the orange color for the call to action about the migration guide on the home page is meant to draw the eye, especially on a home page where the content is largely static, and where directing visitors to the migration guide is an important and transient announcement.

**Comment by rauhul** [comment]
@dempseyatgithub I pulled the banner changes out into #749, could you take a look there?

**Comment by rauhul** [comment]
# Before & After

<details open><summary>Home</summary>

<details open><summary>Light - Default</summary>
Screenshot 2024-06-28 at 3 33 05 PM
</details>

<details open><summary>Light - Increased Contrast</summary>
Screenshot 2024-06-28 at 3 33 12 PM
</details>

<details open><summary>Dark - Default</summary>
Screenshot 2024-06-28 at 3 33 31 PM
</details>

<details open><summary>Dark - Increased Contrast</summary>
Screenshot 2024-06-28 at 3 33 38 PM
</details>

</details>

<details open><summary>Packages</summary>

<details open><summary>Light - Default</summary>
Screenshot 2024-06-28 at 3 40 58 PM
</details>

<details open><summary>Light - Increased Contrast</summary>
Screenshot 2024-06-28 at 3 41 01 PM
</details>

<details open><summary>Dark - Default</summary>
Screenshot 2024-06-28 at 3 41 13 PM
</details>

<details open><summary>Dark - Increased Contrast</summary>
Screenshot 2024-06-28 at 3 41 17 PM
</details>

</details>

<details open><summary>Install</summary>

<details open><summary>Light - Default</summary>
Screenshot 2024-06-28 at 3 34 16 PM
</details>

<details open><summary>Light - Increased Contrast</summary>
Screenshot 2024-06-28 at 3 34 19 PM
</details>

<details open><summary>Dark - Default</summary>
Screenshot 2024-06-28 at 3 34 02 PM
</details>

<details open><summary>Dark - Increased Contrast</summary>
Screenshot 2024-06-28 at 3 34 06 PM
</details>

</details>

**Comment by kubamracek** [comment]
Large +1 from me, this is a big improvement.

**Review by kaishin — CHANGES_REQUESTED** [review]
@rauhul Can we merge the other PRs and rebase before final review? 

That aside, we need to increase the contrast in light mode even further by toning down the background gray, otherwise it would be a regression in accessibility for many.

**Comment by kaishin** [comment]
@rauhul Happy to review this once rebased. Thanks!

**Comment by rauhul** [comment]
@swift-ci please test

**Comment by rauhul** [comment]
anything blocking this?

**Comment by rauhul** [comment]
@swift-ci test

**Comment by rauhul** [comment]
@kaishin any updates?

**Review by kaishin — APPROVED** [review]

**Comment by kaishin** [comment]
@rauhul Feel free to merge after resolving conflicts. I will follow up with another PR to fix Sass deprecation warnings if you can't get to it. cc @federicobucchi

**Comment by rauhul** [comment]
@swift-ci test

**Comment by rauhul** [comment]
@swift-ci test

**Comment by rauhul** [comment]
@swift-ci please test

**Pull request merged**
