### PR TITLE
[Markdown] A few improvements to mentorship page 

### PR DESCRIPTION
**Pull request by AnthonyLatsis**
### Modifications:

* Change heading from "Interest Surveys" to "Participation". The latter
  is a simpler and more catchy word.
* Don't repeat info that is already in the timeline.
* The program duration is measured in weeks. Express time commitment in
  hours/week too.
* Clarify that the exit survey is not compulsory.
* Add link to mentee interest survey

### CODE REVIEW

**Comment by AnthonyLatsis** [comment]
cc @devanshimodha

We posted a link to the mentee interest survey [on the forums](https://forums.swift.org/t/the-2024-swift-mentorship-program/72563/4), so this change is not super urgent, but please consider prioritizing it anyway. Thanks.

**Comment by devanshimodha** [comment]
> cc @devanshimodha
> 
> We posted a link to the mentee interest survey [on the forums](https://forums.swift.org/t/the-2024-swift-mentorship-program/72563/4), so this change is not super urgent, but please consider prioritizing it anyway. Thanks.

Yes, thank you @AnthonyLatsis for putting up the link here as well along with the mentioned changes.

**Review by alexandersandberg — APPROVED** [review]

**Comment by alexandersandberg** [comment]
@swift-ci please test

**Comment by AnthonyLatsis** [comment]
Thanks, Alexander.

**Pull request merged**
