### PR TITLE
Standardize on wide pages

### PR DESCRIPTION
**Pull request by rauhul**
Updates the page templates to use "wide" pages everywhere instead of mix of wide and narrow pages.

### CODE REVIEW

**Comment by rauhul** [comment]
@swift-ci test

**Comment by federicobucchi** [comment]
Didn't we decide to keep the pages with a lot of text narrow (for not having the user to have difficulty on reading) and the ones that allow a "multiple columns" template to have the wide template?

**Comment by rauhul** [comment]
Is this something than can be revisited? The different page width look more like a bug than an intentional choice. Is there some prior art of language sites that act like this?

**Comment by federicobucchi** [comment]
We can chat about it, but it would take a longer discussion.  But, just wanted to let you know, that this was decided for the reason above.  Making all the pages wide, does bring real problems for readers.

**Comment by rauhul** [comment]
How does one join that discussion?

**Comment by federicobucchi** [comment]
We can have the conversation in here, or in https://forums.swift.org

For reference: https://github.com/swiftlang/swift-org-website/pull/499#issuecomment-1913094160

**Comment by rauhul** [comment]
I see, I think the points presented there are fair enough, and probably not worth pushing for a better solution right now

**Review by federicobucchi — CHANGES_REQUESTED** [review]
Ok, please feel free to close the PR

**Pull request closed without merging**
