### PR TITLE
[Release] Swift 6.0

### PR DESCRIPTION
**Pull request by shahmishal**
Swift 6.0 release contains Static SDK for the first time, and we are no longer support Ubuntu 23.10, Ubuntu 18.04, and CentOS 7. 

Screenshot 2024-09-16 at 4 50 59 PM

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Review by 0xTim — APPROVED** [review]

**Comment by shahmishal** [comment]
Docker images waiting on: https://github.com/docker-library/official-images/pull/17571

**Comment by finagolfin** [comment]
@shahmishal, can you pull the static linux SDK for now? See apple/swift-foundation#917, we can put it back up once it's fixed.

**Comment by shahmishal** [comment]
> @shahmishal, can you pull the static linux SDK for now? See [apple/swift-foundation#917](https://github.com/apple/swift-foundation/issues/917), we can put it back up once it's fixed.

We are looking into this issue. Once we have a fix, we can look at the options to publish a new static sdk bundle.

**Pull request merged**
