### PR TITLE
Update package nomination wording

### PR DESCRIPTION
**Pull request by rauhul**

### CODE REVIEW

**Comment by rauhul** [comment]
@swift-ci test

**Comment by daveverwer** [comment]
Hmm. I closed and re-opened it to "unstick" the merge status check but it's still showing this for me:

Screenshot 2024-06-28 at 19 03 27@2x

**Comment by rauhul** [comment]
Odd, I see the same "Checking for ability to merge automatically…".

**Comment by 0xTim** [comment]
It might just be a GH bug

**Comment by daveverwer** [comment]
Seems fixed now! 👍

**Pull request merged**
