### PR TITLE
Update membership of Contributor Membership Workgroup

### PR DESCRIPTION
**Pull request by dempseyatgithub**
Add new workgroup members, James Dempsey and Joseph Heck.

### CODE REVIEW

**Review by shahmishal — APPROVED** [review]

**Comment by shahmishal** [comment]
@swift-ci test

**Review by xedin — COMMENTED** [review]
Thanks! Would you mind removing Max, who recently resigned?

**Comment by dempseyatgithub** [comment]
> Thanks! Would you mind removing Max, who recently resigned?

@xedin Yes, I compared against the workgroup membership on the Swift forums and assumed it was up to date.

I will add an emeritus section similar to other workgroups.

**Comment by dempseyatgithub** [comment]
> > Thanks! Would you mind removing Max, who recently resigned?
> 
> @xedin Yes, I compared against the workgroup membership on the Swift forums and assumed it was up to date.
> 
> I will add an emeritus section similar to other workgroups.

Max had already removed himself from the membership list in a previous PR. I've submitted https://github.com/swiftlang/swift-org-website/pull/800 to add Max in an emeritus member section along the lines of other workgroup pages.

**Pull request merged**
