### PR TITLE
Fixed platform steering group membership

### PR DESCRIPTION
**Pull request by sahilshah7**
Refactoring the hardcoded members list into yml file on platform steering group page: https://www.swift.org/platform-steering-group/

### CODE REVIEW

**Comment by shahmishal** [comment]
@swift-ci test

**Comment by shahmishal** [comment]
cc: @swiftlang/platform-steering-group

**Comment by alexandersandberg** [comment]
Thanks! Do we want to make the same improvement to the other workgroup pages that have not yet been moved to a YAML?

* https://www.swift.org/language-steering-group/ — currently hard-coded as well
* https://www.swift.org/contributor-experience-workgroup/ — we use a table here, but we might want to make it consistent with how the other workgroup members are listed, and only link to their GitHub
*

**Comment by shahmishal** [comment]
Yes, this is a good idea. However, they can be done in a new PR after the changes are merged here.

**Comment by sahilshah7** [comment]
I refactored the hardcoded members list into a YAML file: https://www.swift.org/language-steering-group/ 
I also got rid of the table and refactored the hardcoded members list into a YAML file and only linked their GitHub to make it consistent with how the other workgroup members are listed: https://www.swift.org/contributor-experience-workgroup/

**Comment by alexandersandberg** [comment]
Wonderful, thank you!

Pinging @AnthonyLatsis for a review, as he introduced the table in #621 that we're now removing (although for the better, for the sake of consistency).

**Comment by alexandersandberg** [comment]
@swift-ci please test

**Comment by AnthonyLatsis** [comment]
Sounds good to me. The table is superfluous now that we have both a public GitHub team and forums group for the workgroup; we can point to them instead.

**Pull request merged**
